=head1 NAME

wg-meta - CLI interface

=head1 DESCRIPTION

A CLI interface, implementing L<Wireguard::WGmeta::Wrapper::Config> and L<Wireguard::WGmeta::Wrapper::Show>.

=head1 INSTALLATION

Probably the easiest way is installing the the .deb package from the linked git repo (if you are on debian)

For any other cases: This project supports automake

  autoreconf --install
  ./configure
  make test
  make install

=head1 SYNOPSIS

  sudo wg-meta show
  # output
  interface: wg0
    ListenPort: 51888
    State: UP
    PublicKey: +qz742hzxD3E5z5QF7VOvleVS1onavQpXBK3NdTh40g=

  +peer: WG_0_PEER_A_PUBLIC_KEY
    Name: testero
    Alias: Dual_stack_peer1
    AllowedIPs: fdc9:281f:04d7:9ee9::1/128, 10.0.3.43/32
    endpoint: 147.86.207.49:10400  latest-handshake: >month ago  transfer-rx: 0.26 MiB  transfer-tx: 1.36 MiB
    # end output

  # Access using peer
  sudo wg-meta set wg0 peer +qz742hzxD3E5z5QF7VOvleVS1onavQpXBK3NdTh40g= name Fancy_meta_name

  # Access using alias
  sudo wg-meta set wg0 some_alias description "Some Desc"

  # Disable peer
  sudo wg-meta disable wg0 some_alias

  # Enable peer
  sudo wg-meta enable wg0 +qz742hzxD3E5z5QF7VOvleVS1onavQpXBK3NdTh40g=

  # Apply config
  sudo wg-meta apply wg0

=head1 COPYRIGHT AND LICENSE

MIT License

Copyright (c) 2020 Tobias Bossert

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

